### PR TITLE
verbose mode added

### PR DESCRIPTION
**Pull request by pmpontes**
Support for verbose mode included in response to issue #14

### CODE REVIEW

**Comment by sindresorhus** [comment]
This doesn't correctly handle input when it's a glob as it should then show the resolved files from the glob, not the actual glob pattern. It also does not handle the case where the supplied path doesn't exist as it will still log it as removed.

**Comment by pmpontes** [comment]
I see,  @sindresorhus . The proper way to handle input when it's a glob and also handle the case where the supplied path doesn't exist, would be to make the promise trash returns include an argument specifying a list of the files deleted, otherwise I can't think of another workaround.

**Comment by sindresorhus** [comment]
> would be to make the promise trash returns include an argument specifying a list of the files deleted, otherwise I can't think of another workaround.

Correct, but even that is not that easy as `trash` uses native binaries, so they would have to be modified to return the paths of trashed files too. I'm starting to wonder if it's really worth the effort.

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Review by itfaqtradersnahrianwala-hue — APPROVED** [review]

**Pull request closed without merging**
